credentials:
  usernames:
    Talitha Syifa:
      email: talithasyifa1106@gmail.com
      name: Talitha Syifa
      password: "$2b$12$IF4MRuOyrIyYYl4pV/upMudnR3ySfW3JRGGglWULG1kaD23SY5o9i"

#    user2:
#      email: dosen@email.com
#      name: Dosen Pembimbing
#      password: "$2b$12$A8Kk9ZxQ1U7s2L5F6H8d..."
#
#    mahasiswa:
#      email: mhs@email.com
#      name: Mahasiswa
#      password: "$2b$12$X9LQp8D7kR3F2M1Z6H..."
